# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Boxchat::FooterComponent`.
# Please instead update this file by running `bin/tapioca dsl Boxchat::FooterComponent`.

class Boxchat::FooterComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
