# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Boxchat::FormComponent`.
# Please instead update this file by running `bin/tapioca dsl Boxchat::FormComponent`.

class Boxchat::FormComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
