# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Boxchat::HeaderComponent`.
# Please instead update this file by running `bin/tapioca dsl Boxchat::HeaderComponent`.

class Boxchat::HeaderComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
