# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Boxchat::MessageComponent`.
# Please instead update this file by running `bin/tapioca dsl Boxchat::MessageComponent`.

class Boxchat::MessageComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
