# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Boxchat::MessagesComponent`.
# Please instead update this file by running `bin/tapioca dsl Boxchat::MessagesComponent`.

class Boxchat::MessagesComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
