# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Button::PdfComponent`.
# Please instead update this file by running `bin/tapioca dsl Button::PdfComponent`.

class Button::PdfComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
