# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Button::StickyRightComponent`.
# Please instead update this file by running `bin/tapioca dsl Button::StickyRightComponent`.

class Button::StickyRightComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
