# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `List::OlComponent`.
# Please instead update this file by running `bin/tapioca dsl List::OlComponent`.

class List::OlComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
