# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `List::UlComponent`.
# Please instead update this file by running `bin/tapioca dsl List::UlComponent`.

class List::UlComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
