# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `React::SummaryComponent`.
# Please instead update this file by running `bin/tapioca dsl React::SummaryComponent`.

class React::SummaryComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
