# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `LinkComponent`.
# Please instead update this file by running `bin/tapioca dsl LinkComponent`.

class LinkComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
