require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/branches", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Branch. As you add validations to Branch, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Branch.create! valid_attributes
      get branches_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      branch = Branch.create! valid_attributes
      get branch_url(branch)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_branch_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      branch = Branch.create! valid_attributes
      get edit_branch_url(branch)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Branch" do
        expect {
          post branches_url, params: { branch: valid_attributes }
        }.to change(Branch, :count).by(1)
      end

      it "redirects to the created branch" do
        post branches_url, params: { branch: valid_attributes }
        expect(response).to redirect_to(branch_url(Branch.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Branch" do
        expect {
          post branches_url, params: { branch: invalid_attributes }
        }.to change(Branch, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post branches_url, params: { branch: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested branch" do
        branch = Branch.create! valid_attributes
        patch branch_url(branch), params: { branch: new_attributes }
        branch.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the branch" do
        branch = Branch.create! valid_attributes
        patch branch_url(branch), params: { branch: new_attributes }
        branch.reload
        expect(response).to redirect_to(branch_url(branch))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        branch = Branch.create! valid_attributes
        patch branch_url(branch), params: { branch: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested branch" do
      branch = Branch.create! valid_attributes
      expect {
        delete branch_url(branch)
      }.to change(Branch, :count).by(-1)
    end

    it "redirects to the branches list" do
      branch = Branch.create! valid_attributes
      delete branch_url(branch)
      expect(response).to redirect_to(branches_url)
    end
  end
end
