# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Input::PasswordConfirmationComponent`.
# Please instead update this file by running `bin/tapioca dsl Input::PasswordConfirmationComponent`.

class Input::PasswordConfirmationComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
