# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Input::PasswordComponent`.
# Please instead update this file by running `bin/tapioca dsl Input::PasswordComponent`.

class Input::PasswordComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
