# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Input::RangeComponent`.
# Please instead update this file by running `bin/tapioca dsl Input::RangeComponent`.

class Input::RangeComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
