# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Input::SubmitComponent`.
# Please instead update this file by running `bin/tapioca dsl Input::SubmitComponent`.

class Input::SubmitComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
