# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Input::TextComponent`.
# Please instead update this file by running `bin/tapioca dsl Input::TextComponent`.

class Input::TextComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
