# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Input::TimeComponent`.
# Please instead update this file by running `bin/tapioca dsl Input::TimeComponent`.

class Input::TimeComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
