# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Gallery::DefaultComponent`.
# Please instead update this file by running `bin/tapioca dsl Gallery::DefaultComponent`.

class Gallery::DefaultComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
