# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Body::MainComponent`.
# Please instead update this file by running `bin/tapioca dsl Body::MainComponent`.

class Body::MainComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
