# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Grid::MasonryComponent`.
# Please instead update this file by running `bin/tapioca dsl Grid::MasonryComponent`.

class Grid::MasonryComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
