# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Form::SessionComponent`.
# Please instead update this file by running `bin/tapioca dsl Form::SessionComponent`.

class Form::SessionComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
