# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Icon::BellComponent`.
# Please instead update this file by running `bin/tapioca dsl Icon::BellComponent`.

class Icon::BellComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
