# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Icon::DownloadComponent`.
# Please instead update this file by running `bin/tapioca dsl Icon::DownloadComponent`.

class Icon::DownloadComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
