# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Icon::StarComponent`.
# Please instead update this file by running `bin/tapioca dsl Icon::StarComponent`.

class Icon::StarComponent
  include GeneratedUrlHelpersModule
  include GeneratedPathHelpersModule
end
